package com.aliyun.fsi.insurance.policy.repository.mapper;

import com.aliyun.fsi.insurance.policy.repository.entity.TAgrPolicyQueryRouter;
import com.aliyun.fsi.insurance.policy.repository.entity.TAgrPolicyQueryRouterExample;
import com.aliyun.fsi.insurance.policy.repository.entity.TAgrPolicyQueryRouterKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TAgrPolicyQueryRouterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agr_policy_query_router
     *
     * @mbg.generated
     */
    long countByExample(TAgrPolicyQueryRouterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agr_policy_query_router
     *
     * @mbg.generated
     */
    int deleteByExample(TAgrPolicyQueryRouterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agr_policy_query_router
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(TAgrPolicyQueryRouterKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agr_policy_query_router
     *
     * @mbg.generated
     */
    int insert(TAgrPolicyQueryRouter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agr_policy_query_router
     *
     * @mbg.generated
     */
    int insertSelective(TAgrPolicyQueryRouter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agr_policy_query_router
     *
     * @mbg.generated
     */
    List<TAgrPolicyQueryRouter> selectByExample(TAgrPolicyQueryRouterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agr_policy_query_router
     *
     * @mbg.generated
     */
    TAgrPolicyQueryRouter selectByPrimaryKey(TAgrPolicyQueryRouterKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agr_policy_query_router
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TAgrPolicyQueryRouter record, @Param("example") TAgrPolicyQueryRouterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agr_policy_query_router
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TAgrPolicyQueryRouter record, @Param("example") TAgrPolicyQueryRouterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agr_policy_query_router
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TAgrPolicyQueryRouter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agr_policy_query_router
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TAgrPolicyQueryRouter record);
}