package com.aliyun.fsi.insurance.policy.repository.mapper;

import com.aliyun.fsi.insurance.policy.repository.entity.TAgrInsuredList;
import com.aliyun.fsi.insurance.policy.repository.entity.TAgrInsuredListExample;
import com.aliyun.fsi.insurance.policy.repository.entity.TAgrInsuredListKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TAgrInsuredListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agr_insured_list
     *
     * @mbg.generated
     */
    long countByExample(TAgrInsuredListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agr_insured_list
     *
     * @mbg.generated
     */
    int deleteByExample(TAgrInsuredListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agr_insured_list
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(TAgrInsuredListKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agr_insured_list
     *
     * @mbg.generated
     */
    int insert(TAgrInsuredList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agr_insured_list
     *
     * @mbg.generated
     */
    int insertSelective(TAgrInsuredList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agr_insured_list
     *
     * @mbg.generated
     */
    List<TAgrInsuredList> selectByExampleWithBLOBs(TAgrInsuredListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agr_insured_list
     *
     * @mbg.generated
     */
    List<TAgrInsuredList> selectByExample(TAgrInsuredListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agr_insured_list
     *
     * @mbg.generated
     */
    TAgrInsuredList selectByPrimaryKey(TAgrInsuredListKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agr_insured_list
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TAgrInsuredList record, @Param("example") TAgrInsuredListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agr_insured_list
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") TAgrInsuredList record, @Param("example") TAgrInsuredListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agr_insured_list
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TAgrInsuredList record, @Param("example") TAgrInsuredListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agr_insured_list
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TAgrInsuredList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agr_insured_list
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(TAgrInsuredList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agr_insured_list
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TAgrInsuredList record);
}