package com.mingshashan.learn.learnmybatis.mapper;

import com.mingshashan.learn.learnmybatis.entity.Test02;
import com.mingshashan.learn.learnmybatis.entity.Test02Example;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface Test02Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test02
     *
     * @mbg.generated
     */
    long countByExample(Test02Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test02
     *
     * @mbg.generated
     */
    int deleteByExample(Test02Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test02
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test02
     *
     * @mbg.generated
     */
    int insert(Test02 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test02
     *
     * @mbg.generated
     */
    int insertSelective(Test02 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test02
     *
     * @mbg.generated
     */
    List<Test02> selectByExample(Test02Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test02
     *
     * @mbg.generated
     */
    Test02 selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test02
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Test02 record, @Param("example") Test02Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test02
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Test02 record, @Param("example") Test02Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test02
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Test02 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test02
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Test02 record);
}