#spring.kafka.bootstrap-servers=localhost:9092
#spring.kafka.consumer.group-id=myGroup

server:
  port: 19091
spring:
  kafka:
    bootstrap-servers: 192.168.254.202:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer


custom:
  kafka:
    topic: test