package com.mingshashan.learn.learnmybatis.entity;

import java.io.Serializable;

/**
 * Database Table Remarks:
 *   保单路由表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_agr_policy_query_router
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class TAgrPolicyQueryRouterKey implements Serializable {
    /**
     * Database Column Remarks:
     *   路由查询条件
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_agr_policy_query_router.routing_query_condition
     *
     * @mbg.generated
     */
    private String routingQueryCondition;

    /**
     * Database Column Remarks:
     *   路由查询类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_agr_policy_query_router.routing_query_type_cd
     *
     * @mbg.generated
     */
    private Byte routingQueryTypeCd;

    /**
     * Database Column Remarks:
     *   保单号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_agr_policy_query_router.policy_no
     *
     * @mbg.generated
     */
    private String policyNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_agr_policy_query_router
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_agr_policy_query_router.routing_query_condition
     *
     * @return the value of t_agr_policy_query_router.routing_query_condition
     *
     * @mbg.generated
     */
    public String getRoutingQueryCondition() {
        return routingQueryCondition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_agr_policy_query_router.routing_query_condition
     *
     * @param routingQueryCondition the value for t_agr_policy_query_router.routing_query_condition
     *
     * @mbg.generated
     */
    public void setRoutingQueryCondition(String routingQueryCondition) {
        this.routingQueryCondition = routingQueryCondition == null ? null : routingQueryCondition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_agr_policy_query_router.routing_query_type_cd
     *
     * @return the value of t_agr_policy_query_router.routing_query_type_cd
     *
     * @mbg.generated
     */
    public Byte getRoutingQueryTypeCd() {
        return routingQueryTypeCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_agr_policy_query_router.routing_query_type_cd
     *
     * @param routingQueryTypeCd the value for t_agr_policy_query_router.routing_query_type_cd
     *
     * @mbg.generated
     */
    public void setRoutingQueryTypeCd(Byte routingQueryTypeCd) {
        this.routingQueryTypeCd = routingQueryTypeCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_agr_policy_query_router.policy_no
     *
     * @return the value of t_agr_policy_query_router.policy_no
     *
     * @mbg.generated
     */
    public String getPolicyNo() {
        return policyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_agr_policy_query_router.policy_no
     *
     * @param policyNo the value for t_agr_policy_query_router.policy_no
     *
     * @mbg.generated
     */
    public void setPolicyNo(String policyNo) {
        this.policyNo = policyNo == null ? null : policyNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agr_policy_query_router
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", routingQueryCondition=").append(routingQueryCondition);
        sb.append(", routingQueryTypeCd=").append(routingQueryTypeCd);
        sb.append(", policyNo=").append(policyNo);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}