package com.mingshashan.learn.learnmybatis.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * Database Table Remarks:
 *   保单路由表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_agr_policy_query_router
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class TAgrPolicyQueryRouter extends TAgrPolicyQueryRouterKey implements Serializable {
    /**
     * Database Column Remarks:
     *   ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_agr_policy_query_router.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   产品编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_agr_policy_query_router.product_code
     *
     * @mbg.generated
     */
    private String productCode;

    /**
     * Database Column Remarks:
     *   开始时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_agr_policy_query_router.start_dt
     *
     * @mbg.generated
     */
    private Date startDt;

    /**
     * Database Column Remarks:
     *   结束时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_agr_policy_query_router.end_dt
     *
     * @mbg.generated
     */
    private Date endDt;

    /**
     * Database Column Remarks:
     *   方案编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_agr_policy_query_router.schema_code
     *
     * @mbg.generated
     */
    private String schemaCode;

    /**
     * Database Column Remarks:
     *   渠道编码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_agr_policy_query_router.channel_code
     *
     * @mbg.generated
     */
    private Long channelCode;

    /**
     * Database Column Remarks:
     *   保单所在数据源
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_agr_policy_query_router.policy_data_source_cd
     *
     * @mbg.generated
     */
    private Byte policyDataSourceCd;

    /**
     * Database Column Remarks:
     *   路由项状态
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_agr_policy_query_router.routing_status_cd
     *
     * @mbg.generated
     */
    private Byte routingStatusCd;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_agr_policy_query_router.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     * Database Column Remarks:
     *   修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_agr_policy_query_router.gmt_modified
     *
     * @mbg.generated
     */
    private Date gmtModified;

    /**
     * Database Column Remarks:
     *   是否有效
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_agr_policy_query_router.is_valid
     *
     * @mbg.generated
     */
    private Byte isValid;

    /**
     * Database Column Remarks:
     *   申请份数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_agr_policy_query_router.apply_num
     *
     * @mbg.generated
     */
    private Integer applyNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_agr_policy_query_router
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_agr_policy_query_router.id
     *
     * @return the value of t_agr_policy_query_router.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_agr_policy_query_router.id
     *
     * @param id the value for t_agr_policy_query_router.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_agr_policy_query_router.product_code
     *
     * @return the value of t_agr_policy_query_router.product_code
     *
     * @mbg.generated
     */
    public String getProductCode() {
        return productCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_agr_policy_query_router.product_code
     *
     * @param productCode the value for t_agr_policy_query_router.product_code
     *
     * @mbg.generated
     */
    public void setProductCode(String productCode) {
        this.productCode = productCode == null ? null : productCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_agr_policy_query_router.start_dt
     *
     * @return the value of t_agr_policy_query_router.start_dt
     *
     * @mbg.generated
     */
    public Date getStartDt() {
        return startDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_agr_policy_query_router.start_dt
     *
     * @param startDt the value for t_agr_policy_query_router.start_dt
     *
     * @mbg.generated
     */
    public void setStartDt(Date startDt) {
        this.startDt = startDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_agr_policy_query_router.end_dt
     *
     * @return the value of t_agr_policy_query_router.end_dt
     *
     * @mbg.generated
     */
    public Date getEndDt() {
        return endDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_agr_policy_query_router.end_dt
     *
     * @param endDt the value for t_agr_policy_query_router.end_dt
     *
     * @mbg.generated
     */
    public void setEndDt(Date endDt) {
        this.endDt = endDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_agr_policy_query_router.schema_code
     *
     * @return the value of t_agr_policy_query_router.schema_code
     *
     * @mbg.generated
     */
    public String getSchemaCode() {
        return schemaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_agr_policy_query_router.schema_code
     *
     * @param schemaCode the value for t_agr_policy_query_router.schema_code
     *
     * @mbg.generated
     */
    public void setSchemaCode(String schemaCode) {
        this.schemaCode = schemaCode == null ? null : schemaCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_agr_policy_query_router.channel_code
     *
     * @return the value of t_agr_policy_query_router.channel_code
     *
     * @mbg.generated
     */
    public Long getChannelCode() {
        return channelCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_agr_policy_query_router.channel_code
     *
     * @param channelCode the value for t_agr_policy_query_router.channel_code
     *
     * @mbg.generated
     */
    public void setChannelCode(Long channelCode) {
        this.channelCode = channelCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_agr_policy_query_router.policy_data_source_cd
     *
     * @return the value of t_agr_policy_query_router.policy_data_source_cd
     *
     * @mbg.generated
     */
    public Byte getPolicyDataSourceCd() {
        return policyDataSourceCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_agr_policy_query_router.policy_data_source_cd
     *
     * @param policyDataSourceCd the value for t_agr_policy_query_router.policy_data_source_cd
     *
     * @mbg.generated
     */
    public void setPolicyDataSourceCd(Byte policyDataSourceCd) {
        this.policyDataSourceCd = policyDataSourceCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_agr_policy_query_router.routing_status_cd
     *
     * @return the value of t_agr_policy_query_router.routing_status_cd
     *
     * @mbg.generated
     */
    public Byte getRoutingStatusCd() {
        return routingStatusCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_agr_policy_query_router.routing_status_cd
     *
     * @param routingStatusCd the value for t_agr_policy_query_router.routing_status_cd
     *
     * @mbg.generated
     */
    public void setRoutingStatusCd(Byte routingStatusCd) {
        this.routingStatusCd = routingStatusCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_agr_policy_query_router.gmt_create
     *
     * @return the value of t_agr_policy_query_router.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_agr_policy_query_router.gmt_create
     *
     * @param gmtCreate the value for t_agr_policy_query_router.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_agr_policy_query_router.gmt_modified
     *
     * @return the value of t_agr_policy_query_router.gmt_modified
     *
     * @mbg.generated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_agr_policy_query_router.gmt_modified
     *
     * @param gmtModified the value for t_agr_policy_query_router.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_agr_policy_query_router.is_valid
     *
     * @return the value of t_agr_policy_query_router.is_valid
     *
     * @mbg.generated
     */
    public Byte getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_agr_policy_query_router.is_valid
     *
     * @param isValid the value for t_agr_policy_query_router.is_valid
     *
     * @mbg.generated
     */
    public void setIsValid(Byte isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_agr_policy_query_router.apply_num
     *
     * @return the value of t_agr_policy_query_router.apply_num
     *
     * @mbg.generated
     */
    public Integer getApplyNum() {
        return applyNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_agr_policy_query_router.apply_num
     *
     * @param applyNum the value for t_agr_policy_query_router.apply_num
     *
     * @mbg.generated
     */
    public void setApplyNum(Integer applyNum) {
        this.applyNum = applyNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agr_policy_query_router
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", productCode=").append(productCode);
        sb.append(", startDt=").append(startDt);
        sb.append(", endDt=").append(endDt);
        sb.append(", schemaCode=").append(schemaCode);
        sb.append(", channelCode=").append(channelCode);
        sb.append(", policyDataSourceCd=").append(policyDataSourceCd);
        sb.append(", routingStatusCd=").append(routingStatusCd);
        sb.append(", gmtCreate=").append(gmtCreate);
        sb.append(", gmtModified=").append(gmtModified);
        sb.append(", isValid=").append(isValid);
        sb.append(", applyNum=").append(applyNum);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}