@startuml
'https://plantuml.com/class-diagram

abstract class AbstractList
abstract AbstractCollection
interface List
interface Collection
interface Player

List <|-- AbstractList
Collection <|-- AbstractCollection

Collection <|- List
AbstractCollection <|- AbstractList
AbstractList <|-- ArrayList

Player <|-- XiaoHong
Player <|-- XiaoMing

class ArrayList {
Object[] elementData
size()
}

enum TimeUnit {
DAYS
HOURS
MINUTES
}

class XiaoMing {
    playGame();
}
class XiaoHong {
    Player player;
    playGame();
}

@enduml