package com.aliyun.fsi.insurance.policy.repository.entity;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_agr_insured_list
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class TAgrInsuredList extends TAgrInsuredListKey implements Serializable {
    /**
     * Database Column Remarks:
     *   被保人分组id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_agr_insured_list.insured_group_id
     *
     * @mbg.generated
     */
    private String insuredGroupId;

    /**
     * Database Column Remarks:
     *   被保人userId
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_agr_insured_list.insured_user_id
     *
     * @mbg.generated
     */
    private String insuredUserId;

    /**
     * Database Column Remarks:
     *   保单生效时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_agr_insured_list.policy_start_dt
     *
     * @mbg.generated
     */
    private Date policyStartDt;

    /**
     * Database Column Remarks:
     *   保单结束时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_agr_insured_list.policy_end_dt
     *
     * @mbg.generated
     */
    private Date policyEndDt;

    /**
     * Database Column Remarks:
     *   被保人加入保单时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_agr_insured_list.insured_join_dt
     *
     * @mbg.generated
     */
    private Date insuredJoinDt;

    /**
     * Database Column Remarks:
     *   被保人退出保单时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_agr_insured_list.insured_out_dt
     *
     * @mbg.generated
     */
    private Date insuredOutDt;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_agr_insured_list.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     * Database Column Remarks:
     *   修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_agr_insured_list.gmt_modified
     *
     * @mbg.generated
     */
    private Date gmtModified;

    /**
     * Database Column Remarks:
     *   创建人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_agr_insured_list.creator
     *
     * @mbg.generated
     */
    private String creator;

    /**
     * Database Column Remarks:
     *   修改人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_agr_insured_list.modifier
     *
     * @mbg.generated
     */
    private String modifier;

    /**
     * Database Column Remarks:
     *   有效标识
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_agr_insured_list.is_valid
     *
     * @mbg.generated
     */
    private Byte isValid;

    /**
     * Database Column Remarks:
     *   租户代码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_agr_insured_list.tenant_code
     *
     * @mbg.generated
     */
    private String tenantCode;

    /**
     * Database Column Remarks:
     *   被保人详情
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_agr_insured_list.insured_details
     *
     * @mbg.generated
     */
    private String insuredDetails;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_agr_insured_list
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_agr_insured_list.insured_group_id
     *
     * @return the value of t_agr_insured_list.insured_group_id
     *
     * @mbg.generated
     */
    public String getInsuredGroupId() {
        return insuredGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_agr_insured_list.insured_group_id
     *
     * @param insuredGroupId the value for t_agr_insured_list.insured_group_id
     *
     * @mbg.generated
     */
    public void setInsuredGroupId(String insuredGroupId) {
        this.insuredGroupId = insuredGroupId == null ? null : insuredGroupId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_agr_insured_list.insured_user_id
     *
     * @return the value of t_agr_insured_list.insured_user_id
     *
     * @mbg.generated
     */
    public String getInsuredUserId() {
        return insuredUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_agr_insured_list.insured_user_id
     *
     * @param insuredUserId the value for t_agr_insured_list.insured_user_id
     *
     * @mbg.generated
     */
    public void setInsuredUserId(String insuredUserId) {
        this.insuredUserId = insuredUserId == null ? null : insuredUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_agr_insured_list.policy_start_dt
     *
     * @return the value of t_agr_insured_list.policy_start_dt
     *
     * @mbg.generated
     */
    public Date getPolicyStartDt() {
        return policyStartDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_agr_insured_list.policy_start_dt
     *
     * @param policyStartDt the value for t_agr_insured_list.policy_start_dt
     *
     * @mbg.generated
     */
    public void setPolicyStartDt(Date policyStartDt) {
        this.policyStartDt = policyStartDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_agr_insured_list.policy_end_dt
     *
     * @return the value of t_agr_insured_list.policy_end_dt
     *
     * @mbg.generated
     */
    public Date getPolicyEndDt() {
        return policyEndDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_agr_insured_list.policy_end_dt
     *
     * @param policyEndDt the value for t_agr_insured_list.policy_end_dt
     *
     * @mbg.generated
     */
    public void setPolicyEndDt(Date policyEndDt) {
        this.policyEndDt = policyEndDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_agr_insured_list.insured_join_dt
     *
     * @return the value of t_agr_insured_list.insured_join_dt
     *
     * @mbg.generated
     */
    public Date getInsuredJoinDt() {
        return insuredJoinDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_agr_insured_list.insured_join_dt
     *
     * @param insuredJoinDt the value for t_agr_insured_list.insured_join_dt
     *
     * @mbg.generated
     */
    public void setInsuredJoinDt(Date insuredJoinDt) {
        this.insuredJoinDt = insuredJoinDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_agr_insured_list.insured_out_dt
     *
     * @return the value of t_agr_insured_list.insured_out_dt
     *
     * @mbg.generated
     */
    public Date getInsuredOutDt() {
        return insuredOutDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_agr_insured_list.insured_out_dt
     *
     * @param insuredOutDt the value for t_agr_insured_list.insured_out_dt
     *
     * @mbg.generated
     */
    public void setInsuredOutDt(Date insuredOutDt) {
        this.insuredOutDt = insuredOutDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_agr_insured_list.gmt_create
     *
     * @return the value of t_agr_insured_list.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_agr_insured_list.gmt_create
     *
     * @param gmtCreate the value for t_agr_insured_list.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_agr_insured_list.gmt_modified
     *
     * @return the value of t_agr_insured_list.gmt_modified
     *
     * @mbg.generated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_agr_insured_list.gmt_modified
     *
     * @param gmtModified the value for t_agr_insured_list.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_agr_insured_list.creator
     *
     * @return the value of t_agr_insured_list.creator
     *
     * @mbg.generated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_agr_insured_list.creator
     *
     * @param creator the value for t_agr_insured_list.creator
     *
     * @mbg.generated
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_agr_insured_list.modifier
     *
     * @return the value of t_agr_insured_list.modifier
     *
     * @mbg.generated
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_agr_insured_list.modifier
     *
     * @param modifier the value for t_agr_insured_list.modifier
     *
     * @mbg.generated
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_agr_insured_list.is_valid
     *
     * @return the value of t_agr_insured_list.is_valid
     *
     * @mbg.generated
     */
    public Byte getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_agr_insured_list.is_valid
     *
     * @param isValid the value for t_agr_insured_list.is_valid
     *
     * @mbg.generated
     */
    public void setIsValid(Byte isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_agr_insured_list.tenant_code
     *
     * @return the value of t_agr_insured_list.tenant_code
     *
     * @mbg.generated
     */
    public String getTenantCode() {
        return tenantCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_agr_insured_list.tenant_code
     *
     * @param tenantCode the value for t_agr_insured_list.tenant_code
     *
     * @mbg.generated
     */
    public void setTenantCode(String tenantCode) {
        this.tenantCode = tenantCode == null ? null : tenantCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_agr_insured_list.insured_details
     *
     * @return the value of t_agr_insured_list.insured_details
     *
     * @mbg.generated
     */
    public String getInsuredDetails() {
        return insuredDetails;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_agr_insured_list.insured_details
     *
     * @param insuredDetails the value for t_agr_insured_list.insured_details
     *
     * @mbg.generated
     */
    public void setInsuredDetails(String insuredDetails) {
        this.insuredDetails = insuredDetails == null ? null : insuredDetails.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agr_insured_list
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", insuredGroupId=").append(insuredGroupId);
        sb.append(", insuredUserId=").append(insuredUserId);
        sb.append(", policyStartDt=").append(policyStartDt);
        sb.append(", policyEndDt=").append(policyEndDt);
        sb.append(", insuredJoinDt=").append(insuredJoinDt);
        sb.append(", insuredOutDt=").append(insuredOutDt);
        sb.append(", gmtCreate=").append(gmtCreate);
        sb.append(", gmtModified=").append(gmtModified);
        sb.append(", creator=").append(creator);
        sb.append(", modifier=").append(modifier);
        sb.append(", isValid=").append(isValid);
        sb.append(", tenantCode=").append(tenantCode);
        sb.append(", insuredDetails=").append(insuredDetails);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}