package com.aliyun.fsi.insurance.policy.repository.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TAgrPolicyQueryRouterExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_agr_policy_query_router
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_agr_policy_query_router
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_agr_policy_query_router
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agr_policy_query_router
     *
     * @mbg.generated
     */
    public TAgrPolicyQueryRouterExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agr_policy_query_router
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agr_policy_query_router
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agr_policy_query_router
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agr_policy_query_router
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agr_policy_query_router
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agr_policy_query_router
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agr_policy_query_router
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agr_policy_query_router
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agr_policy_query_router
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agr_policy_query_router
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_agr_policy_query_router
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andRoutingQueryConditionIsNull() {
            addCriterion("routing_query_condition is null");
            return (Criteria) this;
        }

        public Criteria andRoutingQueryConditionIsNotNull() {
            addCriterion("routing_query_condition is not null");
            return (Criteria) this;
        }

        public Criteria andRoutingQueryConditionEqualTo(String value) {
            addCriterion("routing_query_condition =", value, "routingQueryCondition");
            return (Criteria) this;
        }

        public Criteria andRoutingQueryConditionNotEqualTo(String value) {
            addCriterion("routing_query_condition <>", value, "routingQueryCondition");
            return (Criteria) this;
        }

        public Criteria andRoutingQueryConditionGreaterThan(String value) {
            addCriterion("routing_query_condition >", value, "routingQueryCondition");
            return (Criteria) this;
        }

        public Criteria andRoutingQueryConditionGreaterThanOrEqualTo(String value) {
            addCriterion("routing_query_condition >=", value, "routingQueryCondition");
            return (Criteria) this;
        }

        public Criteria andRoutingQueryConditionLessThan(String value) {
            addCriterion("routing_query_condition <", value, "routingQueryCondition");
            return (Criteria) this;
        }

        public Criteria andRoutingQueryConditionLessThanOrEqualTo(String value) {
            addCriterion("routing_query_condition <=", value, "routingQueryCondition");
            return (Criteria) this;
        }

        public Criteria andRoutingQueryConditionLike(String value) {
            addCriterion("routing_query_condition like", value, "routingQueryCondition");
            return (Criteria) this;
        }

        public Criteria andRoutingQueryConditionNotLike(String value) {
            addCriterion("routing_query_condition not like", value, "routingQueryCondition");
            return (Criteria) this;
        }

        public Criteria andRoutingQueryConditionIn(List<String> values) {
            addCriterion("routing_query_condition in", values, "routingQueryCondition");
            return (Criteria) this;
        }

        public Criteria andRoutingQueryConditionNotIn(List<String> values) {
            addCriterion("routing_query_condition not in", values, "routingQueryCondition");
            return (Criteria) this;
        }

        public Criteria andRoutingQueryConditionBetween(String value1, String value2) {
            addCriterion("routing_query_condition between", value1, value2, "routingQueryCondition");
            return (Criteria) this;
        }

        public Criteria andRoutingQueryConditionNotBetween(String value1, String value2) {
            addCriterion("routing_query_condition not between", value1, value2, "routingQueryCondition");
            return (Criteria) this;
        }

        public Criteria andRoutingQueryTypeCdIsNull() {
            addCriterion("routing_query_type_cd is null");
            return (Criteria) this;
        }

        public Criteria andRoutingQueryTypeCdIsNotNull() {
            addCriterion("routing_query_type_cd is not null");
            return (Criteria) this;
        }

        public Criteria andRoutingQueryTypeCdEqualTo(Byte value) {
            addCriterion("routing_query_type_cd =", value, "routingQueryTypeCd");
            return (Criteria) this;
        }

        public Criteria andRoutingQueryTypeCdNotEqualTo(Byte value) {
            addCriterion("routing_query_type_cd <>", value, "routingQueryTypeCd");
            return (Criteria) this;
        }

        public Criteria andRoutingQueryTypeCdGreaterThan(Byte value) {
            addCriterion("routing_query_type_cd >", value, "routingQueryTypeCd");
            return (Criteria) this;
        }

        public Criteria andRoutingQueryTypeCdGreaterThanOrEqualTo(Byte value) {
            addCriterion("routing_query_type_cd >=", value, "routingQueryTypeCd");
            return (Criteria) this;
        }

        public Criteria andRoutingQueryTypeCdLessThan(Byte value) {
            addCriterion("routing_query_type_cd <", value, "routingQueryTypeCd");
            return (Criteria) this;
        }

        public Criteria andRoutingQueryTypeCdLessThanOrEqualTo(Byte value) {
            addCriterion("routing_query_type_cd <=", value, "routingQueryTypeCd");
            return (Criteria) this;
        }

        public Criteria andRoutingQueryTypeCdIn(List<Byte> values) {
            addCriterion("routing_query_type_cd in", values, "routingQueryTypeCd");
            return (Criteria) this;
        }

        public Criteria andRoutingQueryTypeCdNotIn(List<Byte> values) {
            addCriterion("routing_query_type_cd not in", values, "routingQueryTypeCd");
            return (Criteria) this;
        }

        public Criteria andRoutingQueryTypeCdBetween(Byte value1, Byte value2) {
            addCriterion("routing_query_type_cd between", value1, value2, "routingQueryTypeCd");
            return (Criteria) this;
        }

        public Criteria andRoutingQueryTypeCdNotBetween(Byte value1, Byte value2) {
            addCriterion("routing_query_type_cd not between", value1, value2, "routingQueryTypeCd");
            return (Criteria) this;
        }

        public Criteria andPolicyNoIsNull() {
            addCriterion("policy_no is null");
            return (Criteria) this;
        }

        public Criteria andPolicyNoIsNotNull() {
            addCriterion("policy_no is not null");
            return (Criteria) this;
        }

        public Criteria andPolicyNoEqualTo(String value) {
            addCriterion("policy_no =", value, "policyNo");
            return (Criteria) this;
        }

        public Criteria andPolicyNoNotEqualTo(String value) {
            addCriterion("policy_no <>", value, "policyNo");
            return (Criteria) this;
        }

        public Criteria andPolicyNoGreaterThan(String value) {
            addCriterion("policy_no >", value, "policyNo");
            return (Criteria) this;
        }

        public Criteria andPolicyNoGreaterThanOrEqualTo(String value) {
            addCriterion("policy_no >=", value, "policyNo");
            return (Criteria) this;
        }

        public Criteria andPolicyNoLessThan(String value) {
            addCriterion("policy_no <", value, "policyNo");
            return (Criteria) this;
        }

        public Criteria andPolicyNoLessThanOrEqualTo(String value) {
            addCriterion("policy_no <=", value, "policyNo");
            return (Criteria) this;
        }

        public Criteria andPolicyNoLike(String value) {
            addCriterion("policy_no like", value, "policyNo");
            return (Criteria) this;
        }

        public Criteria andPolicyNoNotLike(String value) {
            addCriterion("policy_no not like", value, "policyNo");
            return (Criteria) this;
        }

        public Criteria andPolicyNoIn(List<String> values) {
            addCriterion("policy_no in", values, "policyNo");
            return (Criteria) this;
        }

        public Criteria andPolicyNoNotIn(List<String> values) {
            addCriterion("policy_no not in", values, "policyNo");
            return (Criteria) this;
        }

        public Criteria andPolicyNoBetween(String value1, String value2) {
            addCriterion("policy_no between", value1, value2, "policyNo");
            return (Criteria) this;
        }

        public Criteria andPolicyNoNotBetween(String value1, String value2) {
            addCriterion("policy_no not between", value1, value2, "policyNo");
            return (Criteria) this;
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andProductCodeIsNull() {
            addCriterion("product_code is null");
            return (Criteria) this;
        }

        public Criteria andProductCodeIsNotNull() {
            addCriterion("product_code is not null");
            return (Criteria) this;
        }

        public Criteria andProductCodeEqualTo(String value) {
            addCriterion("product_code =", value, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeNotEqualTo(String value) {
            addCriterion("product_code <>", value, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeGreaterThan(String value) {
            addCriterion("product_code >", value, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeGreaterThanOrEqualTo(String value) {
            addCriterion("product_code >=", value, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeLessThan(String value) {
            addCriterion("product_code <", value, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeLessThanOrEqualTo(String value) {
            addCriterion("product_code <=", value, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeLike(String value) {
            addCriterion("product_code like", value, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeNotLike(String value) {
            addCriterion("product_code not like", value, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeIn(List<String> values) {
            addCriterion("product_code in", values, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeNotIn(List<String> values) {
            addCriterion("product_code not in", values, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeBetween(String value1, String value2) {
            addCriterion("product_code between", value1, value2, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeNotBetween(String value1, String value2) {
            addCriterion("product_code not between", value1, value2, "productCode");
            return (Criteria) this;
        }

        public Criteria andStartDtIsNull() {
            addCriterion("start_dt is null");
            return (Criteria) this;
        }

        public Criteria andStartDtIsNotNull() {
            addCriterion("start_dt is not null");
            return (Criteria) this;
        }

        public Criteria andStartDtEqualTo(Date value) {
            addCriterion("start_dt =", value, "startDt");
            return (Criteria) this;
        }

        public Criteria andStartDtNotEqualTo(Date value) {
            addCriterion("start_dt <>", value, "startDt");
            return (Criteria) this;
        }

        public Criteria andStartDtGreaterThan(Date value) {
            addCriterion("start_dt >", value, "startDt");
            return (Criteria) this;
        }

        public Criteria andStartDtGreaterThanOrEqualTo(Date value) {
            addCriterion("start_dt >=", value, "startDt");
            return (Criteria) this;
        }

        public Criteria andStartDtLessThan(Date value) {
            addCriterion("start_dt <", value, "startDt");
            return (Criteria) this;
        }

        public Criteria andStartDtLessThanOrEqualTo(Date value) {
            addCriterion("start_dt <=", value, "startDt");
            return (Criteria) this;
        }

        public Criteria andStartDtIn(List<Date> values) {
            addCriterion("start_dt in", values, "startDt");
            return (Criteria) this;
        }

        public Criteria andStartDtNotIn(List<Date> values) {
            addCriterion("start_dt not in", values, "startDt");
            return (Criteria) this;
        }

        public Criteria andStartDtBetween(Date value1, Date value2) {
            addCriterion("start_dt between", value1, value2, "startDt");
            return (Criteria) this;
        }

        public Criteria andStartDtNotBetween(Date value1, Date value2) {
            addCriterion("start_dt not between", value1, value2, "startDt");
            return (Criteria) this;
        }

        public Criteria andEndDtIsNull() {
            addCriterion("end_dt is null");
            return (Criteria) this;
        }

        public Criteria andEndDtIsNotNull() {
            addCriterion("end_dt is not null");
            return (Criteria) this;
        }

        public Criteria andEndDtEqualTo(Date value) {
            addCriterion("end_dt =", value, "endDt");
            return (Criteria) this;
        }

        public Criteria andEndDtNotEqualTo(Date value) {
            addCriterion("end_dt <>", value, "endDt");
            return (Criteria) this;
        }

        public Criteria andEndDtGreaterThan(Date value) {
            addCriterion("end_dt >", value, "endDt");
            return (Criteria) this;
        }

        public Criteria andEndDtGreaterThanOrEqualTo(Date value) {
            addCriterion("end_dt >=", value, "endDt");
            return (Criteria) this;
        }

        public Criteria andEndDtLessThan(Date value) {
            addCriterion("end_dt <", value, "endDt");
            return (Criteria) this;
        }

        public Criteria andEndDtLessThanOrEqualTo(Date value) {
            addCriterion("end_dt <=", value, "endDt");
            return (Criteria) this;
        }

        public Criteria andEndDtIn(List<Date> values) {
            addCriterion("end_dt in", values, "endDt");
            return (Criteria) this;
        }

        public Criteria andEndDtNotIn(List<Date> values) {
            addCriterion("end_dt not in", values, "endDt");
            return (Criteria) this;
        }

        public Criteria andEndDtBetween(Date value1, Date value2) {
            addCriterion("end_dt between", value1, value2, "endDt");
            return (Criteria) this;
        }

        public Criteria andEndDtNotBetween(Date value1, Date value2) {
            addCriterion("end_dt not between", value1, value2, "endDt");
            return (Criteria) this;
        }

        public Criteria andSchemaCodeIsNull() {
            addCriterion("schema_code is null");
            return (Criteria) this;
        }

        public Criteria andSchemaCodeIsNotNull() {
            addCriterion("schema_code is not null");
            return (Criteria) this;
        }

        public Criteria andSchemaCodeEqualTo(String value) {
            addCriterion("schema_code =", value, "schemaCode");
            return (Criteria) this;
        }

        public Criteria andSchemaCodeNotEqualTo(String value) {
            addCriterion("schema_code <>", value, "schemaCode");
            return (Criteria) this;
        }

        public Criteria andSchemaCodeGreaterThan(String value) {
            addCriterion("schema_code >", value, "schemaCode");
            return (Criteria) this;
        }

        public Criteria andSchemaCodeGreaterThanOrEqualTo(String value) {
            addCriterion("schema_code >=", value, "schemaCode");
            return (Criteria) this;
        }

        public Criteria andSchemaCodeLessThan(String value) {
            addCriterion("schema_code <", value, "schemaCode");
            return (Criteria) this;
        }

        public Criteria andSchemaCodeLessThanOrEqualTo(String value) {
            addCriterion("schema_code <=", value, "schemaCode");
            return (Criteria) this;
        }

        public Criteria andSchemaCodeLike(String value) {
            addCriterion("schema_code like", value, "schemaCode");
            return (Criteria) this;
        }

        public Criteria andSchemaCodeNotLike(String value) {
            addCriterion("schema_code not like", value, "schemaCode");
            return (Criteria) this;
        }

        public Criteria andSchemaCodeIn(List<String> values) {
            addCriterion("schema_code in", values, "schemaCode");
            return (Criteria) this;
        }

        public Criteria andSchemaCodeNotIn(List<String> values) {
            addCriterion("schema_code not in", values, "schemaCode");
            return (Criteria) this;
        }

        public Criteria andSchemaCodeBetween(String value1, String value2) {
            addCriterion("schema_code between", value1, value2, "schemaCode");
            return (Criteria) this;
        }

        public Criteria andSchemaCodeNotBetween(String value1, String value2) {
            addCriterion("schema_code not between", value1, value2, "schemaCode");
            return (Criteria) this;
        }

        public Criteria andChannelCodeIsNull() {
            addCriterion("channel_code is null");
            return (Criteria) this;
        }

        public Criteria andChannelCodeIsNotNull() {
            addCriterion("channel_code is not null");
            return (Criteria) this;
        }

        public Criteria andChannelCodeEqualTo(Long value) {
            addCriterion("channel_code =", value, "channelCode");
            return (Criteria) this;
        }

        public Criteria andChannelCodeNotEqualTo(Long value) {
            addCriterion("channel_code <>", value, "channelCode");
            return (Criteria) this;
        }

        public Criteria andChannelCodeGreaterThan(Long value) {
            addCriterion("channel_code >", value, "channelCode");
            return (Criteria) this;
        }

        public Criteria andChannelCodeGreaterThanOrEqualTo(Long value) {
            addCriterion("channel_code >=", value, "channelCode");
            return (Criteria) this;
        }

        public Criteria andChannelCodeLessThan(Long value) {
            addCriterion("channel_code <", value, "channelCode");
            return (Criteria) this;
        }

        public Criteria andChannelCodeLessThanOrEqualTo(Long value) {
            addCriterion("channel_code <=", value, "channelCode");
            return (Criteria) this;
        }

        public Criteria andChannelCodeIn(List<Long> values) {
            addCriterion("channel_code in", values, "channelCode");
            return (Criteria) this;
        }

        public Criteria andChannelCodeNotIn(List<Long> values) {
            addCriterion("channel_code not in", values, "channelCode");
            return (Criteria) this;
        }

        public Criteria andChannelCodeBetween(Long value1, Long value2) {
            addCriterion("channel_code between", value1, value2, "channelCode");
            return (Criteria) this;
        }

        public Criteria andChannelCodeNotBetween(Long value1, Long value2) {
            addCriterion("channel_code not between", value1, value2, "channelCode");
            return (Criteria) this;
        }

        public Criteria andPolicyDataSourceCdIsNull() {
            addCriterion("policy_data_source_cd is null");
            return (Criteria) this;
        }

        public Criteria andPolicyDataSourceCdIsNotNull() {
            addCriterion("policy_data_source_cd is not null");
            return (Criteria) this;
        }

        public Criteria andPolicyDataSourceCdEqualTo(Byte value) {
            addCriterion("policy_data_source_cd =", value, "policyDataSourceCd");
            return (Criteria) this;
        }

        public Criteria andPolicyDataSourceCdNotEqualTo(Byte value) {
            addCriterion("policy_data_source_cd <>", value, "policyDataSourceCd");
            return (Criteria) this;
        }

        public Criteria andPolicyDataSourceCdGreaterThan(Byte value) {
            addCriterion("policy_data_source_cd >", value, "policyDataSourceCd");
            return (Criteria) this;
        }

        public Criteria andPolicyDataSourceCdGreaterThanOrEqualTo(Byte value) {
            addCriterion("policy_data_source_cd >=", value, "policyDataSourceCd");
            return (Criteria) this;
        }

        public Criteria andPolicyDataSourceCdLessThan(Byte value) {
            addCriterion("policy_data_source_cd <", value, "policyDataSourceCd");
            return (Criteria) this;
        }

        public Criteria andPolicyDataSourceCdLessThanOrEqualTo(Byte value) {
            addCriterion("policy_data_source_cd <=", value, "policyDataSourceCd");
            return (Criteria) this;
        }

        public Criteria andPolicyDataSourceCdIn(List<Byte> values) {
            addCriterion("policy_data_source_cd in", values, "policyDataSourceCd");
            return (Criteria) this;
        }

        public Criteria andPolicyDataSourceCdNotIn(List<Byte> values) {
            addCriterion("policy_data_source_cd not in", values, "policyDataSourceCd");
            return (Criteria) this;
        }

        public Criteria andPolicyDataSourceCdBetween(Byte value1, Byte value2) {
            addCriterion("policy_data_source_cd between", value1, value2, "policyDataSourceCd");
            return (Criteria) this;
        }

        public Criteria andPolicyDataSourceCdNotBetween(Byte value1, Byte value2) {
            addCriterion("policy_data_source_cd not between", value1, value2, "policyDataSourceCd");
            return (Criteria) this;
        }

        public Criteria andRoutingStatusCdIsNull() {
            addCriterion("routing_status_cd is null");
            return (Criteria) this;
        }

        public Criteria andRoutingStatusCdIsNotNull() {
            addCriterion("routing_status_cd is not null");
            return (Criteria) this;
        }

        public Criteria andRoutingStatusCdEqualTo(Byte value) {
            addCriterion("routing_status_cd =", value, "routingStatusCd");
            return (Criteria) this;
        }

        public Criteria andRoutingStatusCdNotEqualTo(Byte value) {
            addCriterion("routing_status_cd <>", value, "routingStatusCd");
            return (Criteria) this;
        }

        public Criteria andRoutingStatusCdGreaterThan(Byte value) {
            addCriterion("routing_status_cd >", value, "routingStatusCd");
            return (Criteria) this;
        }

        public Criteria andRoutingStatusCdGreaterThanOrEqualTo(Byte value) {
            addCriterion("routing_status_cd >=", value, "routingStatusCd");
            return (Criteria) this;
        }

        public Criteria andRoutingStatusCdLessThan(Byte value) {
            addCriterion("routing_status_cd <", value, "routingStatusCd");
            return (Criteria) this;
        }

        public Criteria andRoutingStatusCdLessThanOrEqualTo(Byte value) {
            addCriterion("routing_status_cd <=", value, "routingStatusCd");
            return (Criteria) this;
        }

        public Criteria andRoutingStatusCdIn(List<Byte> values) {
            addCriterion("routing_status_cd in", values, "routingStatusCd");
            return (Criteria) this;
        }

        public Criteria andRoutingStatusCdNotIn(List<Byte> values) {
            addCriterion("routing_status_cd not in", values, "routingStatusCd");
            return (Criteria) this;
        }

        public Criteria andRoutingStatusCdBetween(Byte value1, Byte value2) {
            addCriterion("routing_status_cd between", value1, value2, "routingStatusCd");
            return (Criteria) this;
        }

        public Criteria andRoutingStatusCdNotBetween(Byte value1, Byte value2) {
            addCriterion("routing_status_cd not between", value1, value2, "routingStatusCd");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIsNull() {
            addCriterion("gmt_create is null");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIsNotNull() {
            addCriterion("gmt_create is not null");
            return (Criteria) this;
        }

        public Criteria andGmtCreateEqualTo(Date value) {
            addCriterion("gmt_create =", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotEqualTo(Date value) {
            addCriterion("gmt_create <>", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThan(Date value) {
            addCriterion("gmt_create >", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThanOrEqualTo(Date value) {
            addCriterion("gmt_create >=", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThan(Date value) {
            addCriterion("gmt_create <", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThanOrEqualTo(Date value) {
            addCriterion("gmt_create <=", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIn(List<Date> values) {
            addCriterion("gmt_create in", values, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotIn(List<Date> values) {
            addCriterion("gmt_create not in", values, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateBetween(Date value1, Date value2) {
            addCriterion("gmt_create between", value1, value2, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotBetween(Date value1, Date value2) {
            addCriterion("gmt_create not between", value1, value2, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIsNull() {
            addCriterion("gmt_modified is null");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIsNotNull() {
            addCriterion("gmt_modified is not null");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedEqualTo(Date value) {
            addCriterion("gmt_modified =", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotEqualTo(Date value) {
            addCriterion("gmt_modified <>", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedGreaterThan(Date value) {
            addCriterion("gmt_modified >", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedGreaterThanOrEqualTo(Date value) {
            addCriterion("gmt_modified >=", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedLessThan(Date value) {
            addCriterion("gmt_modified <", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedLessThanOrEqualTo(Date value) {
            addCriterion("gmt_modified <=", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIn(List<Date> values) {
            addCriterion("gmt_modified in", values, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotIn(List<Date> values) {
            addCriterion("gmt_modified not in", values, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedBetween(Date value1, Date value2) {
            addCriterion("gmt_modified between", value1, value2, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotBetween(Date value1, Date value2) {
            addCriterion("gmt_modified not between", value1, value2, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andIsValidIsNull() {
            addCriterion("is_valid is null");
            return (Criteria) this;
        }

        public Criteria andIsValidIsNotNull() {
            addCriterion("is_valid is not null");
            return (Criteria) this;
        }

        public Criteria andIsValidEqualTo(Byte value) {
            addCriterion("is_valid =", value, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidNotEqualTo(Byte value) {
            addCriterion("is_valid <>", value, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidGreaterThan(Byte value) {
            addCriterion("is_valid >", value, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidGreaterThanOrEqualTo(Byte value) {
            addCriterion("is_valid >=", value, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidLessThan(Byte value) {
            addCriterion("is_valid <", value, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidLessThanOrEqualTo(Byte value) {
            addCriterion("is_valid <=", value, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidIn(List<Byte> values) {
            addCriterion("is_valid in", values, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidNotIn(List<Byte> values) {
            addCriterion("is_valid not in", values, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidBetween(Byte value1, Byte value2) {
            addCriterion("is_valid between", value1, value2, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidNotBetween(Byte value1, Byte value2) {
            addCriterion("is_valid not between", value1, value2, "isValid");
            return (Criteria) this;
        }

        public Criteria andApplyNumIsNull() {
            addCriterion("apply_num is null");
            return (Criteria) this;
        }

        public Criteria andApplyNumIsNotNull() {
            addCriterion("apply_num is not null");
            return (Criteria) this;
        }

        public Criteria andApplyNumEqualTo(Integer value) {
            addCriterion("apply_num =", value, "applyNum");
            return (Criteria) this;
        }

        public Criteria andApplyNumNotEqualTo(Integer value) {
            addCriterion("apply_num <>", value, "applyNum");
            return (Criteria) this;
        }

        public Criteria andApplyNumGreaterThan(Integer value) {
            addCriterion("apply_num >", value, "applyNum");
            return (Criteria) this;
        }

        public Criteria andApplyNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("apply_num >=", value, "applyNum");
            return (Criteria) this;
        }

        public Criteria andApplyNumLessThan(Integer value) {
            addCriterion("apply_num <", value, "applyNum");
            return (Criteria) this;
        }

        public Criteria andApplyNumLessThanOrEqualTo(Integer value) {
            addCriterion("apply_num <=", value, "applyNum");
            return (Criteria) this;
        }

        public Criteria andApplyNumIn(List<Integer> values) {
            addCriterion("apply_num in", values, "applyNum");
            return (Criteria) this;
        }

        public Criteria andApplyNumNotIn(List<Integer> values) {
            addCriterion("apply_num not in", values, "applyNum");
            return (Criteria) this;
        }

        public Criteria andApplyNumBetween(Integer value1, Integer value2) {
            addCriterion("apply_num between", value1, value2, "applyNum");
            return (Criteria) this;
        }

        public Criteria andApplyNumNotBetween(Integer value1, Integer value2) {
            addCriterion("apply_num not between", value1, value2, "applyNum");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_agr_policy_query_router
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_agr_policy_query_router
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}