package com.aliyun.fsi.insurance.policy.repository.entity;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_agr_insured_list
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class TAgrInsuredListKey implements Serializable {
    /**
     * Database Column Remarks:
     *   保单号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_agr_insured_list.policy_no
     *
     * @mbg.generated
     */
    private String policyNo;

    /**
     * Database Column Remarks:
     *   被保人唯一标识
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_agr_insured_list.insured_uid
     *
     * @mbg.generated
     */
    private String insuredUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_agr_insured_list
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_agr_insured_list.policy_no
     *
     * @return the value of t_agr_insured_list.policy_no
     *
     * @mbg.generated
     */
    public String getPolicyNo() {
        return policyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_agr_insured_list.policy_no
     *
     * @param policyNo the value for t_agr_insured_list.policy_no
     *
     * @mbg.generated
     */
    public void setPolicyNo(String policyNo) {
        this.policyNo = policyNo == null ? null : policyNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_agr_insured_list.insured_uid
     *
     * @return the value of t_agr_insured_list.insured_uid
     *
     * @mbg.generated
     */
    public String getInsuredUid() {
        return insuredUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_agr_insured_list.insured_uid
     *
     * @param insuredUid the value for t_agr_insured_list.insured_uid
     *
     * @mbg.generated
     */
    public void setInsuredUid(String insuredUid) {
        this.insuredUid = insuredUid == null ? null : insuredUid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agr_insured_list
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", policyNo=").append(policyNo);
        sb.append(", insuredUid=").append(insuredUid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}