package com.aliyun.fsi.insurance.policy.repository.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TAgrInsuredListExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_agr_insured_list
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_agr_insured_list
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_agr_insured_list
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agr_insured_list
     *
     * @mbg.generated
     */
    public TAgrInsuredListExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agr_insured_list
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agr_insured_list
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agr_insured_list
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agr_insured_list
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agr_insured_list
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agr_insured_list
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agr_insured_list
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agr_insured_list
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agr_insured_list
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agr_insured_list
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_agr_insured_list
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPolicyNoIsNull() {
            addCriterion("policy_no is null");
            return (Criteria) this;
        }

        public Criteria andPolicyNoIsNotNull() {
            addCriterion("policy_no is not null");
            return (Criteria) this;
        }

        public Criteria andPolicyNoEqualTo(String value) {
            addCriterion("policy_no =", value, "policyNo");
            return (Criteria) this;
        }

        public Criteria andPolicyNoNotEqualTo(String value) {
            addCriterion("policy_no <>", value, "policyNo");
            return (Criteria) this;
        }

        public Criteria andPolicyNoGreaterThan(String value) {
            addCriterion("policy_no >", value, "policyNo");
            return (Criteria) this;
        }

        public Criteria andPolicyNoGreaterThanOrEqualTo(String value) {
            addCriterion("policy_no >=", value, "policyNo");
            return (Criteria) this;
        }

        public Criteria andPolicyNoLessThan(String value) {
            addCriterion("policy_no <", value, "policyNo");
            return (Criteria) this;
        }

        public Criteria andPolicyNoLessThanOrEqualTo(String value) {
            addCriterion("policy_no <=", value, "policyNo");
            return (Criteria) this;
        }

        public Criteria andPolicyNoLike(String value) {
            addCriterion("policy_no like", value, "policyNo");
            return (Criteria) this;
        }

        public Criteria andPolicyNoNotLike(String value) {
            addCriterion("policy_no not like", value, "policyNo");
            return (Criteria) this;
        }

        public Criteria andPolicyNoIn(List<String> values) {
            addCriterion("policy_no in", values, "policyNo");
            return (Criteria) this;
        }

        public Criteria andPolicyNoNotIn(List<String> values) {
            addCriterion("policy_no not in", values, "policyNo");
            return (Criteria) this;
        }

        public Criteria andPolicyNoBetween(String value1, String value2) {
            addCriterion("policy_no between", value1, value2, "policyNo");
            return (Criteria) this;
        }

        public Criteria andPolicyNoNotBetween(String value1, String value2) {
            addCriterion("policy_no not between", value1, value2, "policyNo");
            return (Criteria) this;
        }

        public Criteria andInsuredUidIsNull() {
            addCriterion("insured_uid is null");
            return (Criteria) this;
        }

        public Criteria andInsuredUidIsNotNull() {
            addCriterion("insured_uid is not null");
            return (Criteria) this;
        }

        public Criteria andInsuredUidEqualTo(String value) {
            addCriterion("insured_uid =", value, "insuredUid");
            return (Criteria) this;
        }

        public Criteria andInsuredUidNotEqualTo(String value) {
            addCriterion("insured_uid <>", value, "insuredUid");
            return (Criteria) this;
        }

        public Criteria andInsuredUidGreaterThan(String value) {
            addCriterion("insured_uid >", value, "insuredUid");
            return (Criteria) this;
        }

        public Criteria andInsuredUidGreaterThanOrEqualTo(String value) {
            addCriterion("insured_uid >=", value, "insuredUid");
            return (Criteria) this;
        }

        public Criteria andInsuredUidLessThan(String value) {
            addCriterion("insured_uid <", value, "insuredUid");
            return (Criteria) this;
        }

        public Criteria andInsuredUidLessThanOrEqualTo(String value) {
            addCriterion("insured_uid <=", value, "insuredUid");
            return (Criteria) this;
        }

        public Criteria andInsuredUidLike(String value) {
            addCriterion("insured_uid like", value, "insuredUid");
            return (Criteria) this;
        }

        public Criteria andInsuredUidNotLike(String value) {
            addCriterion("insured_uid not like", value, "insuredUid");
            return (Criteria) this;
        }

        public Criteria andInsuredUidIn(List<String> values) {
            addCriterion("insured_uid in", values, "insuredUid");
            return (Criteria) this;
        }

        public Criteria andInsuredUidNotIn(List<String> values) {
            addCriterion("insured_uid not in", values, "insuredUid");
            return (Criteria) this;
        }

        public Criteria andInsuredUidBetween(String value1, String value2) {
            addCriterion("insured_uid between", value1, value2, "insuredUid");
            return (Criteria) this;
        }

        public Criteria andInsuredUidNotBetween(String value1, String value2) {
            addCriterion("insured_uid not between", value1, value2, "insuredUid");
            return (Criteria) this;
        }

        public Criteria andInsuredGroupIdIsNull() {
            addCriterion("insured_group_id is null");
            return (Criteria) this;
        }

        public Criteria andInsuredGroupIdIsNotNull() {
            addCriterion("insured_group_id is not null");
            return (Criteria) this;
        }

        public Criteria andInsuredGroupIdEqualTo(String value) {
            addCriterion("insured_group_id =", value, "insuredGroupId");
            return (Criteria) this;
        }

        public Criteria andInsuredGroupIdNotEqualTo(String value) {
            addCriterion("insured_group_id <>", value, "insuredGroupId");
            return (Criteria) this;
        }

        public Criteria andInsuredGroupIdGreaterThan(String value) {
            addCriterion("insured_group_id >", value, "insuredGroupId");
            return (Criteria) this;
        }

        public Criteria andInsuredGroupIdGreaterThanOrEqualTo(String value) {
            addCriterion("insured_group_id >=", value, "insuredGroupId");
            return (Criteria) this;
        }

        public Criteria andInsuredGroupIdLessThan(String value) {
            addCriterion("insured_group_id <", value, "insuredGroupId");
            return (Criteria) this;
        }

        public Criteria andInsuredGroupIdLessThanOrEqualTo(String value) {
            addCriterion("insured_group_id <=", value, "insuredGroupId");
            return (Criteria) this;
        }

        public Criteria andInsuredGroupIdLike(String value) {
            addCriterion("insured_group_id like", value, "insuredGroupId");
            return (Criteria) this;
        }

        public Criteria andInsuredGroupIdNotLike(String value) {
            addCriterion("insured_group_id not like", value, "insuredGroupId");
            return (Criteria) this;
        }

        public Criteria andInsuredGroupIdIn(List<String> values) {
            addCriterion("insured_group_id in", values, "insuredGroupId");
            return (Criteria) this;
        }

        public Criteria andInsuredGroupIdNotIn(List<String> values) {
            addCriterion("insured_group_id not in", values, "insuredGroupId");
            return (Criteria) this;
        }

        public Criteria andInsuredGroupIdBetween(String value1, String value2) {
            addCriterion("insured_group_id between", value1, value2, "insuredGroupId");
            return (Criteria) this;
        }

        public Criteria andInsuredGroupIdNotBetween(String value1, String value2) {
            addCriterion("insured_group_id not between", value1, value2, "insuredGroupId");
            return (Criteria) this;
        }

        public Criteria andInsuredUserIdIsNull() {
            addCriterion("insured_user_id is null");
            return (Criteria) this;
        }

        public Criteria andInsuredUserIdIsNotNull() {
            addCriterion("insured_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andInsuredUserIdEqualTo(String value) {
            addCriterion("insured_user_id =", value, "insuredUserId");
            return (Criteria) this;
        }

        public Criteria andInsuredUserIdNotEqualTo(String value) {
            addCriterion("insured_user_id <>", value, "insuredUserId");
            return (Criteria) this;
        }

        public Criteria andInsuredUserIdGreaterThan(String value) {
            addCriterion("insured_user_id >", value, "insuredUserId");
            return (Criteria) this;
        }

        public Criteria andInsuredUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("insured_user_id >=", value, "insuredUserId");
            return (Criteria) this;
        }

        public Criteria andInsuredUserIdLessThan(String value) {
            addCriterion("insured_user_id <", value, "insuredUserId");
            return (Criteria) this;
        }

        public Criteria andInsuredUserIdLessThanOrEqualTo(String value) {
            addCriterion("insured_user_id <=", value, "insuredUserId");
            return (Criteria) this;
        }

        public Criteria andInsuredUserIdLike(String value) {
            addCriterion("insured_user_id like", value, "insuredUserId");
            return (Criteria) this;
        }

        public Criteria andInsuredUserIdNotLike(String value) {
            addCriterion("insured_user_id not like", value, "insuredUserId");
            return (Criteria) this;
        }

        public Criteria andInsuredUserIdIn(List<String> values) {
            addCriterion("insured_user_id in", values, "insuredUserId");
            return (Criteria) this;
        }

        public Criteria andInsuredUserIdNotIn(List<String> values) {
            addCriterion("insured_user_id not in", values, "insuredUserId");
            return (Criteria) this;
        }

        public Criteria andInsuredUserIdBetween(String value1, String value2) {
            addCriterion("insured_user_id between", value1, value2, "insuredUserId");
            return (Criteria) this;
        }

        public Criteria andInsuredUserIdNotBetween(String value1, String value2) {
            addCriterion("insured_user_id not between", value1, value2, "insuredUserId");
            return (Criteria) this;
        }

        public Criteria andPolicyStartDtIsNull() {
            addCriterion("policy_start_dt is null");
            return (Criteria) this;
        }

        public Criteria andPolicyStartDtIsNotNull() {
            addCriterion("policy_start_dt is not null");
            return (Criteria) this;
        }

        public Criteria andPolicyStartDtEqualTo(Date value) {
            addCriterion("policy_start_dt =", value, "policyStartDt");
            return (Criteria) this;
        }

        public Criteria andPolicyStartDtNotEqualTo(Date value) {
            addCriterion("policy_start_dt <>", value, "policyStartDt");
            return (Criteria) this;
        }

        public Criteria andPolicyStartDtGreaterThan(Date value) {
            addCriterion("policy_start_dt >", value, "policyStartDt");
            return (Criteria) this;
        }

        public Criteria andPolicyStartDtGreaterThanOrEqualTo(Date value) {
            addCriterion("policy_start_dt >=", value, "policyStartDt");
            return (Criteria) this;
        }

        public Criteria andPolicyStartDtLessThan(Date value) {
            addCriterion("policy_start_dt <", value, "policyStartDt");
            return (Criteria) this;
        }

        public Criteria andPolicyStartDtLessThanOrEqualTo(Date value) {
            addCriterion("policy_start_dt <=", value, "policyStartDt");
            return (Criteria) this;
        }

        public Criteria andPolicyStartDtIn(List<Date> values) {
            addCriterion("policy_start_dt in", values, "policyStartDt");
            return (Criteria) this;
        }

        public Criteria andPolicyStartDtNotIn(List<Date> values) {
            addCriterion("policy_start_dt not in", values, "policyStartDt");
            return (Criteria) this;
        }

        public Criteria andPolicyStartDtBetween(Date value1, Date value2) {
            addCriterion("policy_start_dt between", value1, value2, "policyStartDt");
            return (Criteria) this;
        }

        public Criteria andPolicyStartDtNotBetween(Date value1, Date value2) {
            addCriterion("policy_start_dt not between", value1, value2, "policyStartDt");
            return (Criteria) this;
        }

        public Criteria andPolicyEndDtIsNull() {
            addCriterion("policy_end_dt is null");
            return (Criteria) this;
        }

        public Criteria andPolicyEndDtIsNotNull() {
            addCriterion("policy_end_dt is not null");
            return (Criteria) this;
        }

        public Criteria andPolicyEndDtEqualTo(Date value) {
            addCriterion("policy_end_dt =", value, "policyEndDt");
            return (Criteria) this;
        }

        public Criteria andPolicyEndDtNotEqualTo(Date value) {
            addCriterion("policy_end_dt <>", value, "policyEndDt");
            return (Criteria) this;
        }

        public Criteria andPolicyEndDtGreaterThan(Date value) {
            addCriterion("policy_end_dt >", value, "policyEndDt");
            return (Criteria) this;
        }

        public Criteria andPolicyEndDtGreaterThanOrEqualTo(Date value) {
            addCriterion("policy_end_dt >=", value, "policyEndDt");
            return (Criteria) this;
        }

        public Criteria andPolicyEndDtLessThan(Date value) {
            addCriterion("policy_end_dt <", value, "policyEndDt");
            return (Criteria) this;
        }

        public Criteria andPolicyEndDtLessThanOrEqualTo(Date value) {
            addCriterion("policy_end_dt <=", value, "policyEndDt");
            return (Criteria) this;
        }

        public Criteria andPolicyEndDtIn(List<Date> values) {
            addCriterion("policy_end_dt in", values, "policyEndDt");
            return (Criteria) this;
        }

        public Criteria andPolicyEndDtNotIn(List<Date> values) {
            addCriterion("policy_end_dt not in", values, "policyEndDt");
            return (Criteria) this;
        }

        public Criteria andPolicyEndDtBetween(Date value1, Date value2) {
            addCriterion("policy_end_dt between", value1, value2, "policyEndDt");
            return (Criteria) this;
        }

        public Criteria andPolicyEndDtNotBetween(Date value1, Date value2) {
            addCriterion("policy_end_dt not between", value1, value2, "policyEndDt");
            return (Criteria) this;
        }

        public Criteria andInsuredJoinDtIsNull() {
            addCriterion("insured_join_dt is null");
            return (Criteria) this;
        }

        public Criteria andInsuredJoinDtIsNotNull() {
            addCriterion("insured_join_dt is not null");
            return (Criteria) this;
        }

        public Criteria andInsuredJoinDtEqualTo(Date value) {
            addCriterion("insured_join_dt =", value, "insuredJoinDt");
            return (Criteria) this;
        }

        public Criteria andInsuredJoinDtNotEqualTo(Date value) {
            addCriterion("insured_join_dt <>", value, "insuredJoinDt");
            return (Criteria) this;
        }

        public Criteria andInsuredJoinDtGreaterThan(Date value) {
            addCriterion("insured_join_dt >", value, "insuredJoinDt");
            return (Criteria) this;
        }

        public Criteria andInsuredJoinDtGreaterThanOrEqualTo(Date value) {
            addCriterion("insured_join_dt >=", value, "insuredJoinDt");
            return (Criteria) this;
        }

        public Criteria andInsuredJoinDtLessThan(Date value) {
            addCriterion("insured_join_dt <", value, "insuredJoinDt");
            return (Criteria) this;
        }

        public Criteria andInsuredJoinDtLessThanOrEqualTo(Date value) {
            addCriterion("insured_join_dt <=", value, "insuredJoinDt");
            return (Criteria) this;
        }

        public Criteria andInsuredJoinDtIn(List<Date> values) {
            addCriterion("insured_join_dt in", values, "insuredJoinDt");
            return (Criteria) this;
        }

        public Criteria andInsuredJoinDtNotIn(List<Date> values) {
            addCriterion("insured_join_dt not in", values, "insuredJoinDt");
            return (Criteria) this;
        }

        public Criteria andInsuredJoinDtBetween(Date value1, Date value2) {
            addCriterion("insured_join_dt between", value1, value2, "insuredJoinDt");
            return (Criteria) this;
        }

        public Criteria andInsuredJoinDtNotBetween(Date value1, Date value2) {
            addCriterion("insured_join_dt not between", value1, value2, "insuredJoinDt");
            return (Criteria) this;
        }

        public Criteria andInsuredOutDtIsNull() {
            addCriterion("insured_out_dt is null");
            return (Criteria) this;
        }

        public Criteria andInsuredOutDtIsNotNull() {
            addCriterion("insured_out_dt is not null");
            return (Criteria) this;
        }

        public Criteria andInsuredOutDtEqualTo(Date value) {
            addCriterion("insured_out_dt =", value, "insuredOutDt");
            return (Criteria) this;
        }

        public Criteria andInsuredOutDtNotEqualTo(Date value) {
            addCriterion("insured_out_dt <>", value, "insuredOutDt");
            return (Criteria) this;
        }

        public Criteria andInsuredOutDtGreaterThan(Date value) {
            addCriterion("insured_out_dt >", value, "insuredOutDt");
            return (Criteria) this;
        }

        public Criteria andInsuredOutDtGreaterThanOrEqualTo(Date value) {
            addCriterion("insured_out_dt >=", value, "insuredOutDt");
            return (Criteria) this;
        }

        public Criteria andInsuredOutDtLessThan(Date value) {
            addCriterion("insured_out_dt <", value, "insuredOutDt");
            return (Criteria) this;
        }

        public Criteria andInsuredOutDtLessThanOrEqualTo(Date value) {
            addCriterion("insured_out_dt <=", value, "insuredOutDt");
            return (Criteria) this;
        }

        public Criteria andInsuredOutDtIn(List<Date> values) {
            addCriterion("insured_out_dt in", values, "insuredOutDt");
            return (Criteria) this;
        }

        public Criteria andInsuredOutDtNotIn(List<Date> values) {
            addCriterion("insured_out_dt not in", values, "insuredOutDt");
            return (Criteria) this;
        }

        public Criteria andInsuredOutDtBetween(Date value1, Date value2) {
            addCriterion("insured_out_dt between", value1, value2, "insuredOutDt");
            return (Criteria) this;
        }

        public Criteria andInsuredOutDtNotBetween(Date value1, Date value2) {
            addCriterion("insured_out_dt not between", value1, value2, "insuredOutDt");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIsNull() {
            addCriterion("gmt_create is null");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIsNotNull() {
            addCriterion("gmt_create is not null");
            return (Criteria) this;
        }

        public Criteria andGmtCreateEqualTo(Date value) {
            addCriterion("gmt_create =", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotEqualTo(Date value) {
            addCriterion("gmt_create <>", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThan(Date value) {
            addCriterion("gmt_create >", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThanOrEqualTo(Date value) {
            addCriterion("gmt_create >=", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThan(Date value) {
            addCriterion("gmt_create <", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThanOrEqualTo(Date value) {
            addCriterion("gmt_create <=", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIn(List<Date> values) {
            addCriterion("gmt_create in", values, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotIn(List<Date> values) {
            addCriterion("gmt_create not in", values, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateBetween(Date value1, Date value2) {
            addCriterion("gmt_create between", value1, value2, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotBetween(Date value1, Date value2) {
            addCriterion("gmt_create not between", value1, value2, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIsNull() {
            addCriterion("gmt_modified is null");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIsNotNull() {
            addCriterion("gmt_modified is not null");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedEqualTo(Date value) {
            addCriterion("gmt_modified =", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotEqualTo(Date value) {
            addCriterion("gmt_modified <>", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedGreaterThan(Date value) {
            addCriterion("gmt_modified >", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedGreaterThanOrEqualTo(Date value) {
            addCriterion("gmt_modified >=", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedLessThan(Date value) {
            addCriterion("gmt_modified <", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedLessThanOrEqualTo(Date value) {
            addCriterion("gmt_modified <=", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIn(List<Date> values) {
            addCriterion("gmt_modified in", values, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotIn(List<Date> values) {
            addCriterion("gmt_modified not in", values, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedBetween(Date value1, Date value2) {
            addCriterion("gmt_modified between", value1, value2, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotBetween(Date value1, Date value2) {
            addCriterion("gmt_modified not between", value1, value2, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNull() {
            addCriterion("creator is null");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNotNull() {
            addCriterion("creator is not null");
            return (Criteria) this;
        }

        public Criteria andCreatorEqualTo(String value) {
            addCriterion("creator =", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotEqualTo(String value) {
            addCriterion("creator <>", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThan(String value) {
            addCriterion("creator >", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThanOrEqualTo(String value) {
            addCriterion("creator >=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThan(String value) {
            addCriterion("creator <", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThanOrEqualTo(String value) {
            addCriterion("creator <=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLike(String value) {
            addCriterion("creator like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotLike(String value) {
            addCriterion("creator not like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorIn(List<String> values) {
            addCriterion("creator in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotIn(List<String> values) {
            addCriterion("creator not in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorBetween(String value1, String value2) {
            addCriterion("creator between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotBetween(String value1, String value2) {
            addCriterion("creator not between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andModifierIsNull() {
            addCriterion("modifier is null");
            return (Criteria) this;
        }

        public Criteria andModifierIsNotNull() {
            addCriterion("modifier is not null");
            return (Criteria) this;
        }

        public Criteria andModifierEqualTo(String value) {
            addCriterion("modifier =", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierNotEqualTo(String value) {
            addCriterion("modifier <>", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierGreaterThan(String value) {
            addCriterion("modifier >", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierGreaterThanOrEqualTo(String value) {
            addCriterion("modifier >=", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierLessThan(String value) {
            addCriterion("modifier <", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierLessThanOrEqualTo(String value) {
            addCriterion("modifier <=", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierLike(String value) {
            addCriterion("modifier like", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierNotLike(String value) {
            addCriterion("modifier not like", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierIn(List<String> values) {
            addCriterion("modifier in", values, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierNotIn(List<String> values) {
            addCriterion("modifier not in", values, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierBetween(String value1, String value2) {
            addCriterion("modifier between", value1, value2, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierNotBetween(String value1, String value2) {
            addCriterion("modifier not between", value1, value2, "modifier");
            return (Criteria) this;
        }

        public Criteria andIsValidIsNull() {
            addCriterion("is_valid is null");
            return (Criteria) this;
        }

        public Criteria andIsValidIsNotNull() {
            addCriterion("is_valid is not null");
            return (Criteria) this;
        }

        public Criteria andIsValidEqualTo(Byte value) {
            addCriterion("is_valid =", value, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidNotEqualTo(Byte value) {
            addCriterion("is_valid <>", value, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidGreaterThan(Byte value) {
            addCriterion("is_valid >", value, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidGreaterThanOrEqualTo(Byte value) {
            addCriterion("is_valid >=", value, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidLessThan(Byte value) {
            addCriterion("is_valid <", value, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidLessThanOrEqualTo(Byte value) {
            addCriterion("is_valid <=", value, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidIn(List<Byte> values) {
            addCriterion("is_valid in", values, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidNotIn(List<Byte> values) {
            addCriterion("is_valid not in", values, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidBetween(Byte value1, Byte value2) {
            addCriterion("is_valid between", value1, value2, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidNotBetween(Byte value1, Byte value2) {
            addCriterion("is_valid not between", value1, value2, "isValid");
            return (Criteria) this;
        }

        public Criteria andTenantCodeIsNull() {
            addCriterion("tenant_code is null");
            return (Criteria) this;
        }

        public Criteria andTenantCodeIsNotNull() {
            addCriterion("tenant_code is not null");
            return (Criteria) this;
        }

        public Criteria andTenantCodeEqualTo(String value) {
            addCriterion("tenant_code =", value, "tenantCode");
            return (Criteria) this;
        }

        public Criteria andTenantCodeNotEqualTo(String value) {
            addCriterion("tenant_code <>", value, "tenantCode");
            return (Criteria) this;
        }

        public Criteria andTenantCodeGreaterThan(String value) {
            addCriterion("tenant_code >", value, "tenantCode");
            return (Criteria) this;
        }

        public Criteria andTenantCodeGreaterThanOrEqualTo(String value) {
            addCriterion("tenant_code >=", value, "tenantCode");
            return (Criteria) this;
        }

        public Criteria andTenantCodeLessThan(String value) {
            addCriterion("tenant_code <", value, "tenantCode");
            return (Criteria) this;
        }

        public Criteria andTenantCodeLessThanOrEqualTo(String value) {
            addCriterion("tenant_code <=", value, "tenantCode");
            return (Criteria) this;
        }

        public Criteria andTenantCodeLike(String value) {
            addCriterion("tenant_code like", value, "tenantCode");
            return (Criteria) this;
        }

        public Criteria andTenantCodeNotLike(String value) {
            addCriterion("tenant_code not like", value, "tenantCode");
            return (Criteria) this;
        }

        public Criteria andTenantCodeIn(List<String> values) {
            addCriterion("tenant_code in", values, "tenantCode");
            return (Criteria) this;
        }

        public Criteria andTenantCodeNotIn(List<String> values) {
            addCriterion("tenant_code not in", values, "tenantCode");
            return (Criteria) this;
        }

        public Criteria andTenantCodeBetween(String value1, String value2) {
            addCriterion("tenant_code between", value1, value2, "tenantCode");
            return (Criteria) this;
        }

        public Criteria andTenantCodeNotBetween(String value1, String value2) {
            addCriterion("tenant_code not between", value1, value2, "tenantCode");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_agr_insured_list
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_agr_insured_list
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}